name: 'Update PPA'
description: 'Publish latest version of Gama to the apt repository/ppa'
inputs:
  tag:  
    description: "Release tag name"
    required: true

  is_pre_release:
    description: "Is this a pre-release?"
    default: "false"

runs:
  using: composite
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Login to ghcr.io
      uses: docker/login-action@v3.0.0
      with: 
        registry: ghcr.io
        username: ${{ secrets.BOT_GH_NAME }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push alpha docker image
      if : ${{ steps.pre_release_check.outputs.is_pre_release }} == 'true'
      uses: docker/build-push-action@v5
      working-directory: ./docker/tags/alpha
      with:
        context: . #in /docker/tags/${{ inputs.tag }} thx to working-directory
        push: true
        # GHCR.io replaces docker.pkg.github.com
        tags: |
          ghcr.io/gama-platform/gama:${{ inputs.tag }}
          ghcr.io/gama-platform/gama:alpha

          docker.pkg.github.com/gama-platform/gama.docker/gama:${{ inputs.tag }}
          docker.pkg.github.com/gama-platform/gama.docker/gama:alpha

          gamaplatform/gama:alpha
          gamaplatform/gama:${{ inputs.tag }}

    - name: Change Alpha tag to Stable ${{ inputs.tag }}
      working-directory: ./docker/tags
      shell: bash
      if : ${{ steps.pre_release_check.outputs.is_pre_release }} == 'false'
      run: |
        cp -r alpha ${{ input.tag }}

        cat << EOF > "$GITHUB_STEP_SUMMARY"
        > [!NOTE] FYI 
        > The `tags/alpha` directory has been copied to `[tags/${{ inputs.tag }}](./docker/tags/${{ inputs.tag }})`
        > If you wish to change your Dockerfile for the next alpha version, edit the one located`[tags/alpha](./docker/tags/alpha)`
        > This copy will occur again on the next stable release

        EOF


    - name: Build & Push stable docker image
      if : ${{ steps.pre_release_check.outputs.is_pre_release }} == 'false'
      uses: docker/build-push-action@v5
      working-directory: ./docker/tags/${{ inputs.tag }}
      with:
        context: .
        push: true
        # GHCR.io replaces docker.pkg.github.com
        tags: |
          ghcr.io/gama-platform/gama:${{ inputs.tag }}
          ghcr.io/gama-platform/gama:latest

          docker.pkg.github.com/gama-platform/gama.docker/gama:${{ inputs.tag }}
          docker.pkg.github.com/gama-platform/gama.docker/gama:latest

          gamaplatform/gama:${{ inputs.tag }}
          gamaplatform/gama:latest

